### ISSUE TITLE
Support for JSON Lines

### ISSUE THREAD

**Issue by mlucool** [FGRibreau/jq.node#7] opened 2016-12-20 20:57 UTC
Hi,

I would like to request that jq.node support [JSON lines](http://jsonlines.org/) or simply a stream of ```\n``` separated records.

jq has support for this as follows:
```
$ echo -e '{"foo": "bar"}\n{"baz": "qux"}' | jq '.'
{
  "foo": "bar"
}
{
  "baz": "qux"
}
```

While jq.node (aliased to jqn) has an error:
```
$ echo -e '{"foo": "bar"}\n{"baz": "qux"}' | jqn
undefined:2
{"baz": "qux"}
^

SyntaxError: Unexpected token { in JSON at position 15
```

This support is very useful for things like [bunyan](https://github.com/trentm/node-bunyan) style logs. 

Thanks in advance for looking!

**Comment by FGRibreau** [comment] 2016-12-20 23:46
Hello @mlucool, indeed, your issue is a  duplicate of #6 :)

I will happily accept a PR for it! Closing

**Closed as completed by FGRibreau** 2016-12-20 23:46 UTC
Labels: duplicate

**Comment by mlucool** [comment] 2016-12-20 23:53
Lol we even had the same example....maybe I should read the other issues next time

**Comment by FGRibreau** [comment] 2016-12-21 00:01
@mlucool the issue did not had a description when you posted yours, I just copy/pasted yours and adapted it, so thanks haha ^^

**Comment by mlucool** [comment] 2016-12-21 00:06
:+1:
